spring.application.name=ebankin-backend
spring.datasource.url=jdbc:h2:mem:bank
spring.h2.console.enabled=true
server.port=8085


# JWT Configuration
jwt.secret=9faa372517ac1d389758d3750fc07acf00f542277f26fe5fdfbc1c2f9b703b